import { aiRouter } from "../ai/router.js";
import { workspaceExporter } from "../storage/workspace.js";
import { neo4jStorage } from "../storage/neo4j.js";

export const batchRevisePathologiesDef = {
  name: "batch_revise_pathologies",
  description:
    "Scans a story's diagnostics, triggers a Character Writer's Room debate for failing scenes, and automatically rewrites them based on the characters' feedback.",
  inputSchema: {
    type: "object",
    properties: {
      story_id: { type: "string", description: "The story to batch revise" },
      target_length: {
        type: "string",
        description:
          "The format to recompile the final manuscript into (e.g. screenplay, novel)",
        enum: [
          "short_story",
          "novella",
          "novel",
          "screenplay",
          "book_of_poems",
        ],
        default: "screenplay",
      },
    },
    required: ["story_id"],
  },
};

export async function executeBatchRevisePathologies(args: any) {
  const { story_id, target_length = "screenplay" } = args;

  try {
    const diagnostics = await workspaceExporter.readAllDiagnostics(story_id);
    if (diagnostics.length === 0) {
      return {
        content: [
          { type: "text", text: `No diagnostics found for story: ${story_id}` },
        ],
      };
    }

    const characters = await neo4jStorage.getCharactersForStory(story_id);
    const characterContext =
      characters.length > 0
        ? JSON.stringify(characters, null, 2)
        : "No character profiles found in Graph DB.";

    let revisedCount = 0;

    for (const diag of diagnostics) {
      // 1. Ask the AI to grade the diagnostic report
      const graderPrompt = `Read the following neuro-critique report. Does this scene have significant pathologies, false agency, or pacing flatlines that require a rewrite? Reply with EXACTLY the word "FAIL" if it needs a rewrite, or "PASS" if it is acceptable.\n\nReport:\n${diag.content}`;

      const grade = await aiRouter.generateCompletion({
        taskType: "diagnostic",
        systemPrompt: graderPrompt,
        userMessage: "Grade this report.",
      });

      if (grade.trim().toUpperCase().includes("FAIL")) {
        const draft = await workspaceExporter.readDraft(story_id, diag.sceneId);
        if (!draft) continue;

        // 2. The Character Writer's Room
        const writersRoomPrompt = `You are a Writer's Room composed entirely of the characters from this story.

=== YOUR PROFILES ===
${characterContext}

=== THE FAILED DRAFT ===
${draft}

=== THE DIAGNOSTIC CRITIQUE ===
${diag.content}

TASK:
Write a script/transcript of yourselves (the characters) sitting in a room arguing about why this draft fails.
Argue fiercely to protect your own agency, Jungian archetype, and core desires. E.g., if a character acts like a puppet or cowers when they shouldn't, complain about it! Point out false agency.
At the end of the transcript, output a "UNIFIED CHARACTER DEMANDS" section with bullet points on exactly how the scene must change.`;

        const debateTranscript = await aiRouter.generateCompletion({
          taskType: "brainstorm",
          systemPrompt: writersRoomPrompt,
          userMessage: "Host the Writer's Room debate.",
        });

        // 3. Rewrite the Scene using the debate
        const rewritePrompt = `You are a masterful neurochemical editor. You must rewrite the following scene to fix its pathologies. You MUST strictly obey the "UNIFIED CHARACTER DEMANDS" generated by the characters themselves during their Writer's Room debate.

=== ORIGINAL DRAFT ===
${draft}

=== WRITER'S ROOM DEBATE & DEMANDS ===
${debateTranscript}

Rewrite the scene now. Maintain formatting style.`;

        const rewrittenDraft = await aiRouter.generateCompletion({
          taskType: "generation",
          systemPrompt: rewritePrompt,
          userMessage: "Provide the rewritten scene.",
        });

        await workspaceExporter.saveDraft(
          story_id,
          diag.sceneId,
          rewrittenDraft,
        );
        revisedCount++;
      }
    }

    // 4. Recompile the final manuscript if any scenes were revised
    if (revisedCount > 0) {
      const allDrafts = await workspaceExporter.readAllDrafts(story_id);
      const compilerPrompt = `You are an expert editor and formatter. Compile, rewrite, and stitch the following drafted scenes into a polished, cohesive final manuscript formatted as a ${target_length}. Ensure the formatting matches industry standards for a ${target_length}.\n\n=== DRAFTS ===\n${allDrafts}`;

      const finalManuscript = await aiRouter.generateCompletion({
        taskType: "generation",
        systemPrompt: compilerPrompt,
        userMessage: "Compile the final manuscript.",
      });

      await workspaceExporter.saveManuscript(story_id, finalManuscript);

      return {
        content: [
          {
            type: "text",
            text: `Batch revise complete. ${revisedCount} scenes failed diagnostic and were debated by the characters, rewritten, and recompiled into a new final manuscript for ${story_id}.`,
          },
        ],
      };
    }

    return {
      content: [
        {
          type: "text",
          text: `Batch revise complete. All scenes passed diagnostics for ${story_id}. No rewrites needed.`,
        },
      ],
    };
  } catch (error: any) {
    return {
      content: [
        {
          type: "text",
          text: `Error running batch_revise_pathologies: ${error.message}`,
        },
      ],
      isError: true,
    };
  }
}
